### ISSUE TITLE
Support for Uint8Array for Compress!

### ISSUE THREAD

**Issue by haxorplatform** [nmrugg/LZMA-JS#11]
Hi!
First thank you for being the sole reliable compression I found around for Javascript :)
I have a suggestion to add suport for compressing `Uint8Array` besides `string` in your project.
Inside `lzma_worker.js` I changed the following method
````
function $getChars(this$static, srcBegin, srcEnd, dst, dstBegin) {
		var srcIdx;
		var is_str = this$static.charCodeAt != null;
		for (srcIdx = srcBegin; srcIdx < srcEnd; ++srcIdx) {
			dst[dstBegin++] = is_str ? this$static.charCodeAt(srcIdx) : this$static[srcIdx];
		}
	}
````

This allowed me to compress javascript buffers.
This is a small change, so no need to do a pull request.

Thanks!

**Comment by nmrugg** [comment]
Fixed in 2.1.
