### ISSUE TITLE
Separate compression and decompression

### ISSUE THREAD

**Issue by s-macke** [nmrugg/LZMA-JS#14]
Hi,

for my project 

https://github.com/s-macke/jor1k 
https://github.com/s-macke/jor1k-sysroot

I need a good and fast decompression routine. Currently I am using a simple bzip2 function 
(https://github.com/s-macke/jor1k/blob/master/js/worker/bzip2.js) for this.
To increase the compression ratio and decompression speed I would like to use lzma.
However I don't want to include 130kB of code, in which I am only use a small fraction. 
Is it possible, that you separate those two parts in your code. Either in separate files or to comment very clearly in your source which part is for compression and which is for decompression?

Thanks

**Comment by nmrugg** [comment]
How does 10.5 KB minified (or 4.4 KB gzipped) sound?

Check out 2.0, and let me know if you run into any problems.
