### ISSUE TITLE
Global string object manipulation

### ISSUE THREAD

**Issue by s-macke** [nmrugg/LZMA-JS#15]
The following code lines alter the global string object:
```
    _ = String.prototype;
    _.getClass$ = c;
    _.typeId$ = 2;
```
In my code this leads to some strange behavior in a different part of my program. I am not sure why,
I do not create a worker thread to execute the code.
To manipulate those objects is not a good idea for a library.

**Comment by nmrugg** [comment]
Yeah, sorry about that. Though I am surprised it caused issues.
