### ISSUE TITLE
How can I decompress an LZMA compressed string?

### ISSUE THREAD

**Issue by vinaysshenoy** [nmrugg/LZMA-JS#16]
I have some large LZMA compressed files stored on my server as assets. After downloading(using XMLHttpRequest), I need to decompress them. In my server response, I read the response as a string, but the library doesn't have an option to pass in a string for decompression. What would be the ideal way to achieve this?

**Comment by nmrugg** [comment]
I don't think reading binary data as a string is a good ideal. LZMA-JS 
can read binary data straight from an Ajax request. I just added a demo 
<https://nmrugg.github.io/LZMA-JS/demos/ajax_demo.html> to show how. 
Most browsers support XMLHttpRequest2 <http://caniuse.com/xhr2>.

Does this solve your issue?

The reason why LZMA-JS does not support decoding strings is that they 
tend to corrupt binary data. If you really want to use a string, you 
should be able to loop through the string calling .charCodeAt() to 
create a byte array manually.

**Comment by vinaysshenoy** [comment]
Yes, this works!

Thanks!

I do not know if it was a result of the LZMA decompression, but an extra
whitespace char got added to the beginning of the decompressed string. As a
result, I was not able to parse the extracted string unless I did a trim()
on the string first(it was compressed XML data). Everything worked well
after that.

On Thu, Apr 23, 2015 at 10:27 PM, Nathan Rugg <notifications@github.com>
wrote:

> I don't think reading binary data as a string is a good ideal. LZMA-JS
> can read binary data straight from an Ajax request. I just added a demo
> <https://nmrugg.github.io/LZMA-JS/demos/ajax_demo.html> to show how.
> Most browsers support XMLHttpRequest2 <http://caniuse.com/xhr2>.
>
> Does this solve your issue?
>
> The reason why LZMA-JS does not support decoding strings is that they
> tend to corrupt binary data. If you really want to use a string, you
> should be able to loop through the string calling .charCodeAt() to
> create a byte array manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nmrugg/LZMA-JS/issues/16#issuecomment-95652888>.
>



-- 
Vinay S Shenoy
Software Developer, VR at Stealth Startup
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by nmrugg** [comment]
Cool. I'll close this then.
