### ISSUE TITLE
How is this compared to gzip?

### ISSUE THREAD

**Issue by McFarts** [nmrugg/LZMA-JS#22]
I'm sending data from my websockets gameserver to the client and want to use this to compression method to save bandwidth, looks promising.

The issue I have is, gzip works fine too, but the data that it sends through websocks show up like this:
![](https://i.gyazo.com/26b99cd522baa36b78a99002a7b3b393.png)

Which just won't work.

I think using LZMA and getting the binary looking string type data would be better. How is the performance when decompressing clientside? Negligible right?

What about compressing the data from nodejs compared to compressing the data using gzip, same speed?  ty

**Comment by nmrugg** [comment]
So, typically LZMA will give much smaller results compared to gzip. I just tested the two on my computer and LZMA was 6 times smaller, but your millage will vary depending on the type of data.

The downside, however, is speed. LZMA can much much slower than gzip, like several times slower. (On the server, you can just use the native `lzma` command, of course) I suppose it depends on your needs and where the bottleneck is. Decompressing is <i>much</i> faster, by the way.

You can test the speed here: https://nmrugg.github.io/LZMA-JS/demos/advanced_demo.html

In the future, I hope to support streaming data, which should speed things up as well.

**Comment by McFarts** [comment]
Thanks nmrugg for the reply.  One question though.

The issue I faced with LZMA is I need it to support UTF-16 data set because when I send the compressed data through websockets some characters become invalid.



I used the http://pieroxy.net/blog/pages/lz-string/index.html one here, and used the: compressToUTF16  function and it worked across websockets. which was awesome! 

But, I want to use LMZA because it seems like the compression saves more data.  Maybe you have a different opinion about how I can send the encoded data across websockets, lmk ty!

**Comment by nmrugg** [comment]
socket.io now supports binary data. Have you tried that?

If that doesn't work, I can look into UTF-16 encoding.

**Comment by McFarts** [comment]
yeah binary is alright, but when I pass a lot of my json data for players items/inventory, when using lzma or lzstring it's still a lot less.

it's fine man, only if you have time.  I mean, I'm using the lzstring utf16 right now and it's working, I will definitely keep lzma in the back of my mind ~
