### ISSUE TITLE
lzma-js compatible with lzma?

### ISSUE THREAD

**Issue by tongtwist** [nmrugg/LZMA-JS#23]
Hi, and thanks for your job.

I have a problem with lzma-js and lzma (the linux one)

Here are some scheme to explain my problem:
lzma-js.decompress(lzma(file)) -> file (OK)
lzma-js.decompress(lzma-js.compress(file)) -> file (OK)
lzma.decompress(lzma-js.compress(file)) -> Error "Compressed data are corrupted"

I can see that lzma(file) and lzma-js(file) do not generate the same data with the same parameters.

Do I miss something I need to know when I write the result of lzma-js.compress() in a file?

**Comment by nmrugg** [comment]
You're probably doing something wrong. They should be completely compatible.

Check out the the command line example 
<https://github.com/nmrugg/LZMA-JS/blob/master/bin/lzma.js> for details. 
Perhaps you're missing array2buffer().

If you can't figure it out, you can post some of your code.

**Comment by tongtwist** [comment]
Really sorry,

I just realize it's a mistake in the computer I use to develop. The "lzma" command was a link to "xz" command which use lzma2 and not lzma.

I installed lzma, and now it works.

Sorry and thanks for this lib.
