### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by addaleax** [nmrugg/LZMA-JS#29]
I’m not sure whether I’m overlooking anything, but if I see correctly, currently the only way to know whether an error occurred (e.g. corrupted/truncated input) is to look for global uncaught errors – is that correct? If so, I may be interested in coding a more programmatically accessible approach (e.g. a second `error` parameter to `on_finish`, or something along these lines).

**Comment by nmrugg** [comment]
Yes, error handling is not well done. I've contemplated returning an error but never got the time to implement it. If you are up for it, that would be great!

**Comment by addaleax** [comment]
Okay, I’ll look into that later today :)

**Comment by addaleax** [comment]
Guess this can be closed now – thanks!

**Comment by nmrugg** [comment]
Oh, yeah. I thought it would close automatically. Thanks.
