### ISSUE TITLE
ArrayBuffer seemed to fail

### ISSUE THREAD

**Issue by backspaces** [nmrugg/LZMA-JS#38]
Sorry if this shouldn't be possible, but:

We use a LOT of typed arrays. We want to compress "data tiles", 256x256 arrays of typed data.

I took a test page, included LZMA (btw: works fine in es6 import) using the ArrayBuffer of a TypedArray (Float32Array) and the compress returned just a short array of a dozen ints.

Is there a way to use LZMA with binary data/typed arrays/array buffers?

**Comment by addaleax** [comment]
You should be able to pass `Uint8Array` instances as input to `lzma.compress()` and `lzma.decompress()`.
If you are using the current `master` branch of this repository, the output of `compress()` should also be an `Uint8Array`, and a “normal” `Array` of integers when using the latest published versions.

The type of the output of `decompress()` currently depends on whether your output data would be valid UTF-8, but I guess it would be pretty easy to implement some kind of option that would result in always returning `Uint8Array`s – is that something you would be interested in?

**Comment by backspaces** [comment]
Hi, thanks! I'd prefer Uint8Array as input and output so sounds like I'm in good shape.

Is there a size limit?  I'll be passing in 256x256x4 = 262,144 bytes as the Uint8Array view of the ArrayBuffer. (These are for "data tiles", used by GIS slippy maps, Leaflet for example).

**Comment by addaleax** [comment]
See #39. Also, no, there is no explicit size limit enforced by this library – You should definitely be fine with compressing several megabytes of data.

**Comment by backspaces** [comment]
BTW: I would like decompress to have an option for returning Uint8Array, but the conversion is a single constructor: new Uint8Array(array) so not a big issue.

**Comment by addaleax** [comment]
@backspaces I suppose you are not using the current master here? If you *do* use the current master branch (with the non-minified versions), `my_lzma.decompress(compressedInput, false[, callback])` should give you exactly what you want (and uses TypedArrays internally, too, which improves performance quite a bit).

If you don’t, some clarification on your last comment might be helpful. :)

**Comment by backspaces** [comment]
Hi .. thanks for the info.  Here are the details of my use:

I'm running tests in the browser, w/o workers.  I'm using es6 with modules and babel to transpile only the modules .. es6 is 97% complete on Canary. I use npm with --save-dev, I think no more than a week ago, lzma@2.3.0.  I'm using System.js to load the modules.

To compress I use: `tc = LZMA.compress(tilei, 9)`, where tile's are 256x256 "gis data tiles". These are simple objects with width/height and any type of TypedArray of length of width/height. The "i" in tilei signifies a Uint8Array view onto the tile's ArrayBuffer.

To decompress, I use `LZMA.decompress(tc)` which returns an Array. So I'll do as you suggest .. get the current github master and simply use that.

Thanks for the clear explanation!

BTW: I can use es6 `import LZMA from 'node_modules/lzma/src/lzma_worker.js'` which works just fine, thanks to System.js handling multiple module formats.

**Comment by addaleax** [comment]
Okay, sounds like you should be fine with using the current master. I guess we’ll see when things are ready for a 3.x.x release.

And btw, the Web Worker support of this module is pretty awesome, since compression with LZMA can take quite a bit of time, but I don’t know how well that integrates with System.js and whether asynchronous coding is an acceptable choice for you.

Anyway, I guess I’ll keep this issue in mind and @mention you when there is an official release with support for typed arrays.

**Comment by backspaces** [comment]
Just checking back in.  

I'm using npm's latest which appears the same as the github current master: lzma@2.3.2
> -rw-r--r--@ 1 owen  staff    18K Mar 28 12:13 lzma-c-min.js
-rw-r--r--@ 1 owen  staff    84K Mar 28 12:13 lzma-c.js
-rw-r--r--@ 1 owen  staff   6.8K Mar 28 12:13 lzma-d-min.js
-rw-r--r--@ 1 owen  staff    31K Mar 28 12:13 lzma-d.js
-rw-r--r--@ 1 owen  staff   1.7K Mar 28 12:13 lzma-min.js
-rw-r--r--@ 1 owen  staff   6.4K Mar 28 12:13 lzma.js
-rw-r--r--@ 1 owen  staff    23K Mar 28 12:13 lzma_worker-min.js
-rw-r--r--@ 1 owen  staff   109K Mar 28 12:13 lzma_worker.js

I import via: `import LZMA from 'node_modules/lzma/src/lzma_worker.js'`

I still have the problem that the compress() function returns a JavaScript Array of apparently signed bytes. Here's an example run in the chrome console, with pixels: Uint8Array[65536] the RGBA values from a 128*128*4 image. I presume I could convert it to Int8Array, then Uint8Array:

>pix = LZMA.compress(pixels,9) -> Array[21636]
pixInt8 = new Int8Array(pix) -> Int8Array[21636] 
pixUint8 = new Uint8Array(pixInt8.buffer) -> Uint8Array[21636]

A "diff" of pix & pixInt8 shows them having equal values. So the conversion to pixUint8 should be valid.

Am I somehow doing it wrong? The docs show that I should have LZMA.compress returning a Uint8Array.
