### ISSUE TITLE
Why can not decopress the file compressed by 7-zip tool

### ISSUE THREAD

**Issue by lxq** [nmrugg/LZMA-JS#46]
In windows, I used 7-zip tool compressing a file to *.7z. When using ajax_demo.html go load, it failed.
Why?

Change compressed.txt to compressed.7z, because github does not support 7z file type.
[compressed.txt](https://github.com/nmrugg/LZMA-JS/files/295180/compressed.txt)

**Comment by addaleax** [comment]
7z is a file archive format that contains much more information than .lzma files, such as support for multiple file members and many other features, e.g. compression and even compression methods completely different from LZMA.

**Comment by lxq** [comment]
thank you very much.
